### PR TITLE
rename .src.rpm file to current file name.

### PR DESCRIPTION
**Pull request by mattcheah**
File in this repo: https://github.com/Prajithp/cpanel/raw/master/EA4/ is now named ea-apache24-mod_pagespeed-latest-stable.src.rpm
Changed it in the Readme since I got an error when I tried to follow instructions.

### CODE REVIEW

**Comment by oschaaf** [comment]
That makes sense. Did things work out for you after making this change?

**Comment by oschaaf** [comment]
Ok, in that case it probably doesn't make sense to merge this, right?
Should we close this?

**Comment by mattcheah** [comment]
Not sure if other people will be able to get the instructions working, but
they definitely won't if the URL is pointing to the wrong file.
I think it makes more sense to merge it just to make it more likely that it
will work for others.
There is also another PR that fixes the same problem I think (Sorry, didn't
realize before I made mine), so if you want you can close mine and merge
the other one.

**Comment by oschaaf** [comment]
@mattcheah thanks. I merged https://github.com/apache/incubator-pagespeed-cpanel/pull/48, let's close this one then.

**Pull request closed without merging**
